laravelinstagram/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::resource('/post', 'PostController');
Route::resource('/commit', 'CommitController');
Route::resource('/country', 'CountryController');
Route::get('like/{id}','PostController@like')->name('like');
Route::get('unlike/{id}','PostController@unlike')->name('unlike');
Route::get('/editprofile', 'PostController@editprofile');
Route::put('/updateprofile/{id}','PostController@updateprofile')->name('updateprofile');
Route::get('/image','PostController@image')->name('image');
Route::get('/video','PostController@video')->name('video');

laravelinstagram/resources/views/commitform.blade.php
@extends('layouts.app')
@section('content')
@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('commit.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
{{--                    <input type="hidden" value="{{$post->post_id}}">--}}
                    <div class="form-group">
                        <label for="exampleInputEmail1">Enter Commit</label>
                        <textarea name="commited" id=" commited" cols="80" rows="10"></textarea>
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection

@endsection

laravelinstagram/resources/views/countrydisplay.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="dropdown">
            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                Dropdown button
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                        @foreach($country as $contry)
                                    <a class="dropdown-item" href="{{ route('country.create',['id'=>$contry->id])}}">{{$contry->countryname}}</a>
                                        @endforeach

            </div>

            @foreach($data->posts as $t)
                <div class="container">
                    <div class="card">
                        <div class="card-body col-md-8">

                            <td>
                                <img src="{{url('/storage/'.$t->url)}}" >
                                <h4 class="text-center">Posted By {{$t->user_id}} </h4>
                                <h4  class="text-center"> {{$t->postbody}}</h4>
                        </div>

                    </div>
                    @endforeach
                </div>
        </div>
    </div>
@endsection

laravelinstagram/resources/views/editprofile.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Register') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('updateprofile',[$user->id]) }}"  enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('Name') }}</label>

                                <div class="col-md-6">
                                    <input id="name" type="text" class="form-control @error('name') is-invalid @enderror" name="name" value="{{ $user->name}}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>


                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('dob') }}</label>

                                <div class="col-md-6">
                                    <input id="dob" type="date" class="form-control @error('dob') is-invalid @enderror" name="dob" value="{{ $user->dob}}" required autocomplete="dob" autofocus>

                                    @error('dob')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('profile_pic') }}</label>

                                <div class="col-md-6">
                                    <input id="profile_pic" type="file" class="form-control @error('profile_pic') is-invalid @enderror" name="profile_pic" value="{{ $user->profile_pic}}"  autocomplete="profile_pic" autofocus>

                                    @error('profile_pic')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="name" class="col-md-4 col-form-label text-md-right">{{ __('country_id') }}</label>

                                <div class="col-md-6">
                                    <input id="country_id" type="text" class="form-control @error('country_id') is-invalid @enderror" name="country_id" value="{{ $user->country_id}}" required autocomplete="name" autofocus>

                                    @error('name')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="email" class="col-md-4 col-form-label text-md-right">{{ __('E-Mail Address') }}</label>

                                <div class="col-md-6">
                                    <input id="email" type="email" class="form-control @error('email') is-invalid @enderror" name="email" value="{{ $user->email}}" required autocomplete="email">

                                    @error('email')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="password" class="col-md-4 col-form-label text-md-right">{{ __('Password') }}</label>

                                <div class="col-md-6">
                                    <input id="password" type="password" class="form-control @error('password') is-invalid @enderror" name="password" value="{{ $user->password}}" disabled autocomplete="new-password">

                                    @error('password')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                    @enderror
                                </div>
                            </div>
                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Register') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
@endsection

laravelinstagram/resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

laravelinstagram/resources/views/postdisplay.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <button class="btn btn-primary" ><a href="editprofile" class="text-white">UpdateProfile</a> </button>
        <button class="btn btn-primary" ><a href=" {{ route('post.create') }}  " class="text-white">POST</a> </button>
{{--        <button class="btn btn-primary" ><a href=" {{ route(' country.create') }}  " class="text-white">CountryWisepost</a> </button>--}}
        <button class="btn btn-primary" ><a href=" {{ route('image') }}  " class="text-white">image</a> </button>
        <button class="btn btn-primary" ><a href=" {{ route('video') }} " class="text-white">video</a> </button>
    </div>
    <div class="container">
        <div class="col-md-9 offset-2">
    @foreach($post as $post1)
        <div class="container">
       <div class="card">
           <div class="card-body">
               <td>
                   <img src="{{url('/storage/'.$post1->url)}}" >
                   <h4 class="text-center">Posted By {{$post1->user_id}} </h4>
                   <h4  class="text-center"> {{$post1->postbody}}</h4>
           </div>
           <div class="card-footer">
               <div class="text-center">
                   <button class="btn btn-primary text-white"><a href="{{ route('commit.create',$post1->id) }}" class="text-white"> Comment </a> </button>

                   @if(sizeof($post1->user)  == null)
                       <a href="{{url("/like/{$post1->id}")}}" class="btn btn-sm btn-success">like</a>
                   @else
                       <a href="{{url("/unlike/{$post1->id}")}}" class="btn btn-sm btn-danger">Unlike</a>
                   @endif
               @if(Auth::id()==$post1->id)
                  <form action="{{route('post.destroy',$post1->id)}}" method="POST">
                       @csrf
                       @method('DELETE')
                   <button class="btn btn-success">delete</button>
                   </form>
                     @endif
               </div>
           </div>
           </div>
    @endforeach
        </div>
    </div>
    </div>
@endsection

laravelinstagram/resources/views/postform.blade.php
@extends('layouts.app')

@section('content')
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form action="{{ route('post.store')}}" method="POST" enctype="multipart/form-data">
                    @csrf
                    <div class="form-group">
                        <label for="exampleInputEmail1">Enter Post</label>
                        <input type="file" class="form-control" id="exampleInputEmail1"  name="url" aria-describedby="emailHelp">

                    </div>
                    <div class="form-group">
                        <label for="exampleInputPassword1">Description</label>
                        <input type="text" class="form-control" id="exampleInputPassword1" name="postbody" placeholder="description">
                    </div>

                    <button type="submit" class="btn btn-primary">Submit</button>
                </form>
            </div>
        </div>
    </div>
@endsection